### ISSUE TITLE
change

### ISSUE THREAD

**Issue by booom691** [Dendrowen/Blobifier#1]
nice project, but I recommend a change

Mount it on the back of the profile and rotate the servo so that it is on top. This way, the nozzle can be cleaned without having to change the height of the Z-axis (Voron 2.4). Print it in two parts to adjust the nozzle height, similar to the Klicky probe

![change](https://github.com/Dendrowen/Blobifier/assets/46597578/ca47be80-a101-4f59-82f5-fd4371be8337)

**Comment by Dendrowen** [comment]
In that case the brush and bucket would also need gantry mounting, which is getting a bit much. The bucket would then als need to be a lot smaller which defeats the purpose for this device. Thanks for your input though!
