### ISSUE TITLE
kinematic mounts

### ISSUE THREAD

**Issue by jckennell** [Dendrowen/Blobifier#10]
for the bases for the people with kinematic bed mounts, there are 2 poplular sets that people use. the mounts from Mandela Roseworks sits the bed higher than the whoppingpochard kinematic mounts. i modified mine to 55.4mm tall (16.7mm taller than the original base). also the shaker arm needs to be 16.7mm taller for beds that sit higher, as well as the nozzle brush.
![shaker arm](https://github.com/Dendrowen/Blobifier/assets/83933850/35ebff13-8f9e-4a3b-be3b-22d69f1be1e1)

**Comment by Dendrowen** [comment]
Thanks! Did you create this in the .step or .f3z files?

**Comment by jckennell** [comment]
I used your .step file. My Fusion skills aren't very good, but basically just added a block on top of the arm and and put the holes in it. I should have saved it, but I didn't because I'm using Fusions free hobby license, which only let's me save so many files. So the ones that get deleted are the most simple ones to recreate if I have to. I just posted the Pic for reference as to what I did for that part.

**Comment by Dendrowen** [comment]
Makes sense. Do you still have the .STL, and if so. could you create a pull request or send it to me on Discord?

**Comment by jckennell** [comment]
I messaged you on the discord. Github is witchcraft to me. I've tried adding files, pull requests, branches, forks. It's all beyond me. LolSent from my T-Mobile 5G Device
-------- Original message --------From: Dendrowen ***@***.***> Date: 3/7/24  6:49 AM  (GMT-05:00) To: Dendrowen/Blobifier ***@***.***> Cc: jckennell ***@***.***>, Manual ***@***.***> Subject: Re: [Dendrowen/Blobifier] kinematic mounts (Issue #10) 
Makes sense. Do you still have the .STL, and if so. could you create a pull request or send it to me on Discord?

**Comment by Dendrowen** [comment]
Files are added. Thank you very much!
