### ISSUE TITLE
.step does not include tray part

### ISSUE THREAD

**Issue by 53Aries** [Dendrowen/Blobifier#11]
Just fyi. Thanks.

**Comment by Garr-Garr** [comment]
It looks like it's included:

> https://github.com/Dendrowen/Blobifier/blob/main/Source%20files/Blobifier.step

![image](https://github.com/Dendrowen/Blobifier/assets/52166834/4bb84294-e047-44b5-a6b7-3074eef5d5d6)

**Comment by 53Aries** [comment]
> It looks like it's included:
> 
> > https://github.com/Dendrowen/Blobifier/blob/main/Source%20files/Blobifier.step
> 
> ![image](https://private-user-images.githubusercontent.com/52166834/327201642-4bb84294-e047-44b5-a6b7-3074eef5d5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjM4OTUsIm5iZiI6MTcxOTk2MzU5NSwicGF0aCI6Ii81MjE2NjgzNC8zMjcyMDE2NDItNGJiODQyOTQtZTA0Ny00NGI1LWE2YjctMzA3NGVlZjVkNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDIzMzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOGFlMTg4ZjA0ZTlhY2YxNGY1OTc1Njk1Yzk3YTkyODZlYWJkZTY4MDA5NzgzNGQzYmRiNmVkOGMyNjE2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcVohx2AoRmyhijQn_Ca5I1drO7TMbKNq5-sspMXvVo)

I don't see it. By tray im referring to blob tray connected to the servo. 
![Screenshot 2024-07-02 184041](https://github.com/Dendrowen/Blobifier/assets/110708581/c401bed8-f801-471d-a2bb-05f6929e1b71)
