### ISSUE TITLE
Blobifier start position Z height issue

### ISSUE THREAD

**Issue by PaulMellor** [Dendrowen/Blobifier#17]
Whilst testing the Blobifier I found that with a beacon, it does not account for the brush height when moving from z homing position to the brush start position causing it to short out the Beacon terminals, as keeps everything at the same height and just moves the xy. 
Can we make it check the current Z height and ensure it is above the Brush height plus 2mm. to ensure it does not cause a short or avoidable collision with objects. 
I am assuming it is not an issue with printing as assume it would do a z hop before moving. I haven't gotten to this part of testing still tuning things.

**Comment by Dendrowen** [comment]
I'm reluctant on adding too many alterations to accommodate other mods. You could overwrite the macro in and make sure it's above the brush and then calling the original
