### ISSUE TITLE
Gantry mount

### ISSUE THREAD

**Issue by Maximus2711** [Dendrowen/Blobifier#18]
It seems like ultimate solution for purging, like collaboration blobifier and eap project.

**Comment by Dendrowen** [comment]
Not possible due to the needed z travel relative to the blobifier base. Sorry.

**Comment by baracoder** [comment]
:thinking: Maybe it could work. Here is my idea: The base is mounted at an angle and instead of Z, the toolhead can move in X or Y direction while extruding away from it. What do you think?

**Comment by Dendrowen** [comment]
I say, go ahead and try. I think there are better solutions for this but the Blobifier isn't really designed for that.
