### ISSUE TITLE
Servo return in neutral position when not ussed after "in" command

### ISSUE THREAD

**Issue by kktonev** [Dendrowen/Blobifier#19]
It looks like this line makes servo to turn in neutral (middle) position:
SET_SERVO SERVO=blobifier WIDTH=0

I try almo any other settings - no change.
Also I try different servos - no change.
After this line is executed almost any 1 of 5 execution of "BLOBIFIER_SERVO POS=in"
leads to non-requried movement of the servo.

Its very likely to be seen when set higher value for "variable_dwell_time:".
I make it 1200. Its clearly hearable when the servo is turned off.
So it turns in neutral with more delay if the value is bigger, but there is no change in this behaiveier.

UPDATE:
I comment out the line:
SET_SERVO SERVO=blobifier WIDTH=0

I think is not a problem, because I use external 5V supply for all the servos.

**Comment by Seleadlab** [comment]
Set the variable_dwell_time in gcode_macro BLOBIFIER_SERVO to 0
