### ISSUE TITLE
Fusion file has a lost sketch plane issue

### ISSUE THREAD

**Issue by jwhite** [Dendrowen/Blobifier#23]
Sketch plane was lost here:
![image](https://github.com/Dendrowen/Blobifier/assets/473577/d59458d8-432b-45a7-90d0-2f1d6eadbb72)

Likely this was done when the work was done to create different bed widths.

**Comment by Dendrowen** [comment]
yeah. I'm quite the F360 beginner. No clue on how to fix this.
