### ISSUE TITLE
Sovol Sv08

### ISSUE THREAD

**Issue by checkitog** [Dendrowen/Blobifier#27]
Hi friend, I have a sovol sv08 with ercf, could blobifier be adapted for this machine?

**Comment by Dendrowen** [comment]
I believe spoke to you on discord? It probably can, but I don't have one to test it and find it a bit unnecessary.

**Comment by checkitog** [comment]
I made my own design for the purges, and my own bucket, it is a design without servo, but I can't get the macro to respond the way I need it to.
