### ISSUE TITLE
Filament stays in hotend when bucket is full.

### ISSUE THREAD

**Issue by tdchaos** [Dendrowen/Blobifier#32]
When the bucker gets full the toolhead parks without retracting the filament. Then the print is paused, leaving the filament to cook and clog.

Filament ahould get cut or tip formed before pausing.

![20240924_071013](https://github.com/user-attachments/assets/000db57f-c662-4c13-a71c-14465b6eec56)

**Comment by Dendrowen** [comment]
Doesn't your idle_timeout turn off your hotend preventing this?
