### ISSUE TITLE
Servo_arm_???.stl

### ISSUE THREAD

**Issue by evelyndooley** [Dendrowen/Blobifier#5]
Wondering where these files are. They're mentioned in the README but don't seem to appear in the repo. May have forgotten a `git add` ;)

**Comment by Dendrowen** [comment]
Oh, your absolutely right! I'll add them. I didn't think of it anymore because I'm using the provided servo arm.

**Comment by ksteddom** [comment]
I'm having trouble getting the Servo_Arm.stl to fit a MG90S servo. It sticks up too high and interferes with the tray sliding. I have verified that the servo is completely seated in the slot and the arm is pressed all the way down. @Dendrowen do you mean to say you are using one of the servo arms that comes with the servo or the newer Servo_Arm.stl file?

**Comment by Dendrowen** [comment]
I'm using the included servo arm atm. That one seems to work fine for me. Did you print it in the provided orientation?

**Comment by ksteddom** [comment]
Thanks for the clarification. I thought I printed it correctly. I’m going to print it again to double check. If I have any more issues  I’ll start a new thread.
