### ISSUE TITLE
`Blobifier.cfg` has incorrect indenting

### ISSUE THREAD

**Issue by ejsears** [Dendrowen/Blobifier#7]
The following lines are incorrectly indented in the `blobifier.cfg` file and result in the following errors:

```
Source contains parsing errors: '/home/eric/printer_data/config/hardware/blobifier.cfg'
	[line 356]: 'M220 S{backup_feedrate * 100}\n```
```

Line 356: `M220 S{backup_feedrate * 100}`

```
Option '{% set raise_z_min' is not valid in section 'delayed_gcode blobifier_init'
```

Line 467: `{% set raise_z_min = (bl.iteration_z_raise - ((bl.max_iterations_per_blob - 1) * (bl.max_iterations_per_blob) / 2) * bl.iteration_z_change) %}`

```
Option 'blobifier_servo pos' is not valid in section 'delayed_gcode blobifier_init'
```
Line 486: `BLOBIFIER_SERVO POS=out`

**Comment by ejsears** [comment]
Opened a PR at https://github.com/Dendrowen/Blobifier/pull/8 if it is easier for you.

**Comment by Dendrowen** [comment]
Merged. Ty
